name: Deploy WebApp
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ vars.DOCKER_USERNAME }}/deploy-uap:latest --push .
        env:
          DOCKER_BUILDKIT: 1

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.REMOTE_SERVER }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ vars.DOCKER_USERNAME }}/deploy-uap:latest
            docker run -d -p 80:3000 --name webapp --restart unless-stopped ${{ vars.DOCKER_USERNAME }}/deploy-uap:latest
