name: Deploy WebApp
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/deploy-uap:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/deploy-uap:latest
        env:
          DOCKER_BUILDKIT: 1

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_SERVER }} "docker pull ${{ secrets.DOCKER_USERNAME }}/deploy-uap:latest && docker-compose down && docker-compose up -d"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
